name: musicians_shop
description: Musicians Shop
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  get: 4.6.1

  # Firebase
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.15
  flutterfire_cli: ^0.2.2+2
  firebase_storage: ^10.2.16

  # UI
  fluttertoast: ^8.0.9
  cupertino_icons: ^1.0.4

  # Utils
  mime: ^1.0.2
  url_launcher: ^6.1.2
  image_picker: ^0.8.5+3
  package_info_plus: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  flutter_launcher_icons_maker: ^0.10.2

flutter_icons:
  web: true
  ios: true
  macos: true
  linux: true
  windows: true
  android: true
  remove_alpha_ios: true
  adaptive_icon_background: '#FFFFFF'
  image_path: 'assets/app_icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/
