name: musicians_shop
description: Musicians Shop
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  get: ^4.6.5

  # Firebase
  firebase_core: ^1.18.0
  firebase_auth: ^3.3.20
  cloud_firestore: ^3.1.18
  flutterfire_cli: ^0.2.2+2
  firebase_storage: ^10.2.18
  firebase_messaging: ^11.4.2
  firebase_analytics: ^9.1.10
  firebase_crashlytics: ^2.8.2

  # UI
  overlay_support: ^2.0.1
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.5
  syncfusion_flutter_charts: ^20.1.61

  # Utils
  mime: ^1.0.2
  logger: ^1.1.0
  file_picker: ^4.6.1
  url_strategy: ^0.2.0
  url_launcher: ^6.1.4
  path_provider: ^2.0.11
  package_info_plus: ^1.4.2
  android_path_provider: ^0.3.0
  flutter_local_notifications: ^9.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons_maker: ^0.10.2

flutter_icons:
  web: true
  ios: true
  macos: true
  linux: true
  windows: true
  android: true
  remove_alpha_ios: true
  adaptive_icon_background: '#FFFFFF'
  image_path: 'assets/app_icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/
