// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBhPNzsu450AraKSTxED4vv73I0teR4FU',
    appId: '1:670066810894:web:90e98f3d393ac6b41fdc5f',
    messagingSenderId: '670066810894',
    projectId: 'g-shop-4fe02',
    authDomain: 'g-shop-4fe02.firebaseapp.com',
    storageBucket: 'g-shop-4fe02.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPhZ7a8o1SEEw2Hlq5CMSAgUKe685UTdE',
    appId: '1:670066810894:android:ad4fb3523daea2a51fdc5f',
    messagingSenderId: '670066810894',
    projectId: 'g-shop-4fe02',
    storageBucket: 'g-shop-4fe02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt_sLvEo7xMr0xfC9qgKNuN3m0CKACDm4',
    appId: '1:670066810894:ios:c49cc74c8d0301041fdc5f',
    messagingSenderId: '670066810894',
    projectId: 'g-shop-4fe02',
    storageBucket: 'g-shop-4fe02.appspot.com',
    androidClientId: '670066810894-12ur49v29vt91dmluo7lp0s70tem98iu.apps.googleusercontent.com',
    iosClientId: '670066810894-evt71gs7j4q4rjnqmcrsir42bjdk0ktp.apps.googleusercontent.com',
    iosBundleId: 'com.example.musiciansShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt_sLvEo7xMr0xfC9qgKNuN3m0CKACDm4',
    appId: '1:670066810894:ios:c49cc74c8d0301041fdc5f',
    messagingSenderId: '670066810894',
    projectId: 'g-shop-4fe02',
    storageBucket: 'g-shop-4fe02.appspot.com',
    androidClientId: '670066810894-12ur49v29vt91dmluo7lp0s70tem98iu.apps.googleusercontent.com',
    iosClientId: '670066810894-evt71gs7j4q4rjnqmcrsir42bjdk0ktp.apps.googleusercontent.com',
    iosBundleId: 'com.example.musiciansShop',
  );
}
